### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by yudi-mars** [guoyang9/NFM-pyorch#1]
Can u tell me what is the exact meaning of each column in `ml-tag.train.libfm` file?

**Comment by guoyang9** [comment]
This code is mainly designed for tackling the implicit feedback problem in recommendation. To this end, the rating is normalized into {-1, 1}, where -1 denotes there is no interaction between the user and the item, while 1 denotes opposite. 

Therefore, the first value is the ground-truth rating, following by a series of feature id (before semicolon) and feature value (after semicolon).
